[target.x86_64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-fuse-ld=lld"
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-fuse-ld=/opt/homebrew/Cellar/lld/19.1.1/bin/ld64.lld"
]